---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30088
    name: frontend

  - protocol: TCP
    port: 50000
    nodePort: 30050
    name: idkyet